apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.elasticsearch.service.name }}
spec:
  selector:
    app: {{ .Values.elasticsearch.service.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.elasticsearch.service.port }}
      targetPort: {{ .Values.elasticsearch.service.port }}