# logstash-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.logstash.service.name }}
spec:
  selector:
    app: {{ .Values.logstash.service.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.logstash.service.port }}
      targetPort: {{ .Values.logstash.service.port }}