# mongo-db-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongodb.service.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    app: {{ .Values.mongodb.service.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.mongodb.service.port }}
      targetPort: {{ .Values.mongodb.service.port }}
