# mysql-db-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysqldb.service.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.mysqldb.service.name }}
spec:
  ports:
    - port: {{ .Values.mysqldb.service.port }}
      targetPort: {{ .Values.mysqldb.service.port }}
      protocol: TCP
      name: {{ .Values.mysqldb.service.name }}-port
  selector:
    app: {{ .Values.mysqldb.service.name }}
  type: ClusterIP