# redis-cache-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis-cache-service.name }}
  namespace: development
  labels:
    app: {{ .Values.redis-cache-service.name }}
spec:
  ports:
    - port: {{ .Values.redis-cache-service.port }}
      targetPort: {{ .Values.redis-cache-service.port }}
      protocol: TCP
      name: {{ .Values.redis-cache-service.name }}-port
  selector:
    app: {{ .Values.redis-cache-service.name }}
  type: ClusterIP