# zookeeper-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.zookeeper-service.name }}
  namespace: development
spec:
  selector:
    app: {{ .Values.zookeeper-service.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.zookeeper-service.port }}
      targetPort: {{ .Values.zookeeper-service.port }}
