# api-gateway-microservice-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.api-gateway-microservice.name }}
  namespace: development
  labels:
    app: {{ .Values.api-gateway-microservice.name }}
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.api-gateway-microservice.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.api-gateway-microservice.name }}
    spec:
      restartPolicy: Always
      containers:
        - name: {{ .Values.api-gateway-microservice.name }}
          image: docker.io/{{ .Values.docker.user }}/{{ .Values.api-gateway-microservice.name }}:{{ .Values.api-gateway-microservice.version }}
          resources:
            requests:
              cpu: "100m"
          imagePullPolicy: IfNotPresent #Always
          ports:
            - containerPort: {{ .Values.api-gateway-microservice.port }}
          env:
            - name: SERVICE_CLASSES
              value: "http://classes-microservice:8080"
            - name: SERVICE_DOCUMENTS
              value: "http://documents-microservice:8081"
            - name: SERVICE_SECURITY
              value: "http://security-microservice:8082"
            - name: SERVER_PORT
              value: {{ .Values.api-gateway-microservice.port }}
            # TODO ajustar LOGGING_LEVEL