# classes-microservice-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.classes-microservice.name }}
  namespace: development
  labels:
    app: {{ .Values.classes-microservice.name }}
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.classes-microservice.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.classes-microservice.name }}
    spec:
      restartPolicy: Always
      containers:
        - name: {{ .Values.classes-microservice.name }}
          image: docker.io/{{ .Values.docker-hub.user }}/{{ .Values.classes-microservice.name }}:{{ .Values.classes-microservice.version }}
          resources:
            requests:
              cpu: "100m"
          imagePullPolicy: IfNotPresent #Always
          ports:
            - containerPort: {{ .Values.classes-microservice.port }}
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql:3306/classes"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "password"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "create-drop"
            - name: SPRING_JPA_SHOW_SQL
              value: "true"
            - name: SPRING_JPA_HIBERNATE_DIALECT
              value: "org.hibernate.dialect.MySQLDialect"
            - name: SERVER_PORT
              value: {{ .Values.classes-microservice.port }}
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-service:9092"
            - name: SPRING_REDIS_HOST
              value: "redis-cache"
            - name: SPRING_REDIS_PORT
              value: "6379"