# kibana-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.kibana.service.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.kibana.service.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.kibana.service.name }}
    spec:
      containers:
        - name: {{ .Values.kibana.service.name }}
          image: {{ .Values.kibana.service.image }}
          ports:
            - containerPort: {{ .Values.kibana.service.port }}
          env:
            - name: ELASTICSEARCH_HOST
              value: "elasticsearch"
            - name: ELASTICSEARCH_PORT
              value: "9200"