# mongo-db-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mongo-db-service.name }}
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.mongo-db-service.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.mongo-db-service.name }}
    spec:
      containers:
        - name: {{ .Values.mongo-db-service.name }}
          image: mongo:latest
          ports:
            - containerPort: {{ .Values.mongo-db-service.port }}
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: adrian
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: password
