# mysql-db-security-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mysql-db-security-service.name }}
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.mysql-db-security-service.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.mysql-db-security-service.name }}
    spec:
      containers:
        - name: {{ .Values.mysql-db-security-service.name }}
          image: mysql:8.0
          ports:
            - containerPort: {{ .Values.mysql-db-security-service.port }}
          env:
            - name: MYSQL_DATABASE
              value: security
            - name: MYSQL_ROOT_PASSWORD
              value: password
