# security-microservice-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.security-microservice.name }}
  namespace: development
  labels:
    app: {{ .Values.security-microservice.name }}
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.security-microservice.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.security-microservice.name }}
    spec:
      restartPolicy: Always
      containers:
        - name: {{ .Values.security-microservice.name }}
          image: docker.io/{{ .Values.docker-hub.user }}/{{ .Values.security-microservice.name }}:{{ .Values.security-microservice.version }}
          resources:
            requests:
              cpu: "100m"
          imagePullPolicy: IfNotPresent #Always
          ports:
            - containerPort: {{ .Values.security-microservice.port }}
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql-db-security:3306/security?allowPublicKeyRetrieval=true&useSSL=false"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "password"
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
              value: "org.hibernate.dialect.MySQLDialect"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "create-drop"
            - name: APP_JWT_SECRET
              value: "======================Adrian=Spring==========================="
            - name: APP_JWT_EXPIRATION_MS
              value: "86400000"
            - name: SERVER_PORT
              value: {{ .Values.security-microservice.port }}
            - name: SPRING_REDIS_HOST
              value: "redis-cache"
            - name: SPRING_REDIS_PORT
              value: "6379"