# mysql connection uri
spring.datasource.url=jdbc:mysql://localhost:3306/classes

# mysql auth
spring.datasource.username=root
spring.datasource.password=password

# jpa logging and db restart
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect

# running server port
server.port = 8080
