project_name               = "crossfitapp"
vpc_cidr                   = "192.168.0.0/16"
vpc_name                   = "crossfitapp"
public_subnets_cidr        = ["192.168.0.0/24", "192.168.1.0/24"]
private_subnets_cidr       = ["192.168.4.0/24", "192.168.5.0/24"]
zone                       = "us-west-1"
availability_zones_public  = ["us-west-1a", "us-west-1b"]
availability_zones_private = ["us-west-1a", "us-west-1b"]
cidr_block-internet_gw     = "0.0.0.0/0"
cidr_block-nat_gw          = "0.0.0.0/0"
secret_id                  = "adrian"
identifier                 = "crossfitapp"
allocated_storage          = 5
storage_type               = "gp2"
engine                     = "postgres"
engine_version             = 13.7
instance_class             = "db.t2.micro"
database_name              = "crossfitapp"
github_username            = "adrianrevilla009"
github_repository_url      = "https://github.com/adrianrevilla009/crossfit-app-TFM"
