variable "project_name" {}
#variable "vpc_cidr" {}
#variable "vpc_name" {}
#variable "public_subnets_cidr" {}
#variable "availability_zones_public" {}
#variable "private_subnets_cidr" {}
variable "zone" {}
#variable "availability_zones_private" {}
#variable "cidr_block-internet_gw" {}
#variable "cidr_block-nat_gw" {}
#variable "secret_id" {}
#variable "secret_pass" {}
#variable "identifier" {}
#variable "allocated_storage" {}
#variable "storage_type" {}
#variable "engine" {}
#variable "engine_version" {}
#variable "instance_class" {}
#variable "database_name" {}
#variable "github_token" {}
#variable "github_username" {}
#variable "github_repository_url" {}
variable "ami" {}
