apiVersion: v1
kind: Secret
metadata:
  name: argocd-repo-secret
  namespace: argocd
type: kubernetes.io/basic-auth
stringData:
  username: adrianrevilla009
  password: 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
