apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-gateway-microservice
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: development
  project: default
  source:
    repoURL: 'https://adrianrevilla009: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@github.com/adrianrevilla009/crossfit-app-TFM.git'
    path: 'helm/app/templates'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
