apiVersion: v1
kind: Secret
metadata:
  name: argocd-repo-secret
  namespace: argocd
type: kubernetes.io/basic-auth
stringData:
  username: adrianrevilla009
  password: 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
