apiVersion: v1
kind: Secret
metadata:
  name: argocd-repo-secret
  namespace: argocd
type: kubernetes.io/basic-auth
stringData:
  username: adrianrevilla009
  password: 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
