apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossfit-app-tfm
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: development
  project: default
  source:
    repoURL: 'https://adrianrevilla009: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@github.com/adrianrevilla009/crossfit-app-TFM.git'
    path: 'helm/app'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
