# mongo connection uri
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=documents

# mongo auth
spring.data.mongodb.username=root
spring.data.mongodb.password=password

# jpa logging and db restart
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# avoid jpa auto configuration
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration 

# running server port
server.port = 8081

# kafka message producer
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer


