# mongo auth and uri
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=documents
spring.data.mongodb.username=adrian
spring.data.mongodb.password=password
spring.data.mongodb.authentication-database=admin

# jpa logging and db restart
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# avoid jpa auto configuration
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# running server port
server.port = 8081

# kafka message producer
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# documents generation
documents.generation.path=documents-microservice/src/main/resources/static/
documents.generation.name=classes-excel.xlsx

# redis
spring.redis.host=localhost
spring.redis.port=6379

# prometheus
management.endpoints.web.exposure.include=*
management.endpoint.metrics.enabled=true
management.metrics.export.prometheus.enabled=true
