# api-gateway-microservice-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.apigateway.microservice.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.apigateway.microservice.name }}
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.apigateway.microservice.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.apigateway.microservice.name }}
    spec:
      restartPolicy: Always
      containers:
        - name: {{ .Values.apigateway.microservice.name }}
          image: docker.io/{{ .Values.dockerhub.user }}/{{ .Values.apigateway.microservice.name }}:{{ .Values.apigateway.microservice.version }}
          resources:
            requests:
              cpu: "100m"
          imagePullPolicy: IfNotPresent #Always
          ports:
            - containerPort: {{ .Values.apigateway.microservice.port }}
          env:
            - name: SERVICE_CLASSES
              value: "http://classes-microservice:8080"
            - name: SERVICE_DOCUMENTS
              value: "http://documents-microservice:8081"
            - name: SERVICE_SECURITY
              value: "http://security-microservice:8082"
            - name: SERVER_PORT
              value: "8083"
            # TODO ajustar LOGGING_LEVEL