# documents-microservice-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.documents.microservice.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.documents.microservice.name }}
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.documents.microservice.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.documents.microservice.name }}
    spec:
      restartPolicy: Always
      containers:
        - name: {{ .Values.documents.microservice.name }}
          image: docker.io/{{ .Values.dockerhub.user }}/{{ .Values.documents.microservice.name }}:{{ .Values.documents.microservice.version }}
          resources:
            requests:
              cpu: "100m"
          imagePullPolicy: IfNotPresent #Always
          ports:
            - containerPort: {{ .Values.documents.microservice.port }}
          env:
            - name: SPRING_DATA_MONGODB_HOST
              value: "mongo-db"
            - name: SPRING_DATA_MONGODB_PORT
              value: "27017"
            - name: SPRING_DATA_MONGODB_DATABASE
              value: "documents"
            - name: SPRING_DATA_MONGODB_USERNAME
              value: "adrian"
            - name: SPRING_DATA_MONGODB_PASSWORD
              value: "password"
            - name: SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE
              value: "admin"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "create-drop"
            - name: SPRING_JPA_SHOW_SQL
              value: "true"
            - name: SPRING_AUTOCONFIGURE_EXCLUDE
              value: "org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration"
            - name: SERVER_PORT
              value: "8081"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-service:9092"
            - name: DOCUMENTS_GENERATION_PATH
              value: "documents-microservice/src/main/resources/static/"
            - name: DOCUMENTS_GENERATION_NAME
              value: "classes-excel.xlsx"
            - name: SPRING_REDIS_HOST
              value: "redis-cache"
            - name: SPRING_REDIS_PORT
              value: "6379"
          volumeMounts:
            - name: document-volume
              mountPath: /documents
          volumes:
            - name: document-volume
              persistentVolumeClaim:
                claimName: document-pvc