# mysql-db-security-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mysqldb.security.service.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.mysqldb.security.service.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.mysqldb.security.service.name }}
    spec:
      containers:
        - name: {{ .Values.mysqldb.security.service.name }}
          image: {{ .Values.mysqldb.security.service.image }}
          ports:
            - containerPort: {{ .Values.mysqldb.security.service.port }}
          env:
            - name: MYSQL_DATABASE
              value: "security"
            - name: MYSQL_ROOT_PASSWORD
              value: "password"
