apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-gateway-to-security
  namespace: development
spec:
  podSelector:
    matchLabels:
      app: api-gateway-microservice
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: security-microservice
      ports:
        - port: 8082