apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-gateway-microservice
  namespace: development
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: api-gateway-microservice
  endpoints:
    - port: "8083"
      path: /actuator/prometheus
      scheme: http
      interval: 15s  # Puedes ajustar el intervalo según tus necesidades
