name: Build and Push Docker Images

on:
  push:
    branches:
      - develop

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - api-gateway-microservice

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Maven
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Clean and Install Dependencies
        working-directory: ./${{ matrix.service }}
        run: |
            # Da permisos de ejecución a mvnw si es necesario
            chmod +x mvnw
            
            # Ejecuta mvn clean install para limpiar e instalar dependencias
            ./mvnw clean install    

      - name: Run Tests
        working-directory: ./${{ matrix.service }}
        run: |
          # Da permisos de ejecución a mvnw si es necesario
          chmod +x mvnw
          
          # Ejecuta las pruebas utilizando Maven Wrapper
          ./mvnw test

  build-and-push:
    name: Generate images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Read and Increment Version
        id: version
        run: |
          versionFile="version.txt"
          if [ ! -f $versionFile ]; then
          echo "v1" > $versionFile
          fi
          currentVersion=$(cat $versionFile)
          # Extrae el número de versión sin el prefijo "v"
          currentVersionNumber=$(echo $currentVersion | sed 's/v//')
          nextVersionNumber=$((currentVersionNumber + 1))
          nextVersion="v$nextVersionNumber"
          echo $nextVersion > $versionFile
          
          # Exporta la variable de entorno con la nueva versión
          echo "VERSION=$nextVersion" >> $GITHUB_ENV

      - name: Acceder a la Variable de Entorno
        run: echo $VERSION

      # This is needed to avoid iterative CI after committing version
      - name: Check if Skip CI
        run: |
          if git log --format=%B -n 1 $GITHUB_SHA | grep -q '\[skip ci\]'; then
            echo "CI skip detected. Exiting..."
            exit 78
          fi

      - name: Commit & Push changes
        uses: devops-infra/action-commit-push@master
        with:
          github_token: "${{ secrets.TOKEN }}"
          add_timestamp: true
          commit_prefix: "[AUTO]"
          commit_message: "Update version to $VERSION [skip ci]"
          force: false
          target_branch: version-${{ steps.version.outputs.VERSION }}

      # Merge to main does not have to be automated
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "Update version to $VERSION [skip ci]"
          title: "[AUTO] Bump version to $VERSION"
          labels: "auto-merge"
          branch: version-${{ steps.version.outputs.VERSION }}
          delete-branch: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Images
        run: |
          services=("api-gateway-microservice" "classes-microservice" "documents-microservice" "security-microservice")

          for service in "${services[@]}"; do
            echo "Current directory: $(pwd)"
            ls -la
            cd $service
            echo "Changed to directory: $(pwd)"
            ls -la
            docker buildx create --use
            docker buildx inspect --bootstrap
            docker buildx build -f dockerfile.Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/$service:$VERSION --push .
            cd ..
          done

  sonar-cloud:
    name: Analize code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu' # Alternative distribution options are available.
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=adrianrevilla009_crossfit-app-TFM

