name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Read and Increment Version
        id: version
        run: |
          versionFile="version.txt"
          if [ ! -f $versionFile ]; then
          echo "v1" > $versionFile
          fi
          currentVersion=$(cat $versionFile)
          # Extrae el número de versión sin el prefijo "v"
          currentVersionNumber=$(echo $currentVersion | sed 's/v//')
          nextVersionNumber=$((currentVersionNumber + 1))
          nextVersion="v$nextVersionNumber"
          echo $nextVersion > $versionFile
          
          # Exporta la variable de entorno con la nueva versión
          echo "VERSION=$nextVersion" >> $GITHUB_ENV

      - name: Acceder a la Variable de Entorno
        run: echo $VERSION

      - name: Check if Skip CI
        run: |
          if git log --format=%B -n 1 $GITHUB_SHA | grep -q '\[skip ci\]'; then
            echo "CI skip detected. Exiting..."
            exit 78
          fi

      - name: Commit & Push changes
        if: github.event_name == 'push' && github.event.ref == 'refs/heads/main' && github.actor != 'github-actions[bot]'
        run: |
          git config user.email "${{ github.actor }}@github.com"
          git config user.name "${{ github.actor }}"
          echo "[skip ci]" >> version.txt
          git add version.txt
          git commit -m "Update version to $VERSION [skip ci]"
          git push origin main

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Images
        run: |
          services=("api-gateway-microservice" "classes-microservice" "documents-microservice" "security-microservice")

          for service in "${services[@]}"; do
            echo "Current directory: $(pwd)"
            ls -la
            cd $service
            echo "Changed to directory: $(pwd)"
            ls -la
            docker buildx create --use
            docker buildx inspect --bootstrap
            docker buildx build -f dockerfile.Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/$service:$VERSION --push .
            cd ..
          done
    

